In [34]:
#下面开始介绍DataFrame，就是pandas里面的二位数据结构
import pandas as pd
# dataframe要求每一列可以是不同的数据类型，但是同一列的话必须是同一种数据类型
# 相当于是每一列都是一个Series
s1=pd.Series([1,2,4,6,7])
s2=pd.Series([9,10,65,78,90])
df=pd.DataFrame({"第一列":s1,"第二列":s2},index=[2,3,4,0,1],columns=['第二列','第一列'])# 需要按照字典的方式创建Dataframe
df
#注意创建DataFrame的时候，index默认从0开始，index填入的数值就是要展示的行数以及顺序
# 同理，columns要填入的数值就是要展示的列的顺序以及展示那些列

   第二列  第一列
2   65    4
3   78    6
4   90    7
0    9    1
1   10    2

In [15]:
# 关于DataFrame的属性操作
print(f"data的行索引：{df.index}")
print(f"data的列索引：{df.columns}")
df.T
print(df.T.index,df.T.columns)

data的行索引：Index([2, 3, 4, 0, 1], dtype='int64')
data的列索引：Index(['第二列'], dtype='str')
Index(['第二列'], dtype='str') Index([2, 3, 4, 0, 1], dtype='int64')

In [31]:
# 关于DataFrame的索引操作，loc iloc at，其中loc是显示操作，iloc就是隐式操作
print(df.loc[4])
print(df.iloc[3])

df
#获取某一列操作
print(df.loc[:,'第二列'])
print(df.iloc[:,0])# 使用隐式位置来索引第一列的数据



#使用at与iat来获取某一个具体的数值
print(df.at[4,'第二列'])
print(df.iat[2,0])

第二列    90
Name: 4, dtype: int64
第二列    9
Name: 0, dtype: int64
2    65
3    78
4    90
0     9
1    10
Name: 第二列, dtype: int64
2    65
3    78
4    90
0     9
1    10
Name: 第二列, dtype: int64
90
90

In [ ]:
#也可以使用index直接获取某一列的数据
print(df['第二列'])
print(df.第二列)# 居然还可以这样子


# 获取多列数据，就需要使用两层括号，返回的是一个dataframe
print(df[['第一列','第二列']])
df[['第一列','第二列']]

# 使用head与tail函数也是可以看到这个部分数据的
# 同时也是可以使用bool索引的,中括号写法也可以，不过要加上这个字符串
# df[df.第二列>40]
df[df['第二列']>40]# 和上面的操作一模一样

2    65
3    78
4    90
0     9
1    10
Name: 第二列, dtype: int64
2    65
3    78
4    90
0     9
1    10
Name: 第二列, dtype: int64
   第一列  第二列
2    4   65
3    6   78
4    7   90
0    1    9
1    2   10

   第二列  第一列
2   65    4
3   78    6
4   90    7

In [67]:
data={
    '姓名':['张三','王五','赵六','招黑','数学'],
    '数学':[90,100,132,147,150],
    '语文':[100,130,145,128,139],
    '英语':[30,45,98,78,100]
}
scores=pd.DataFrame(data)
scores
#计算每一位学生的总分，并新增加一列数据
scores.iloc[:,1:].sum(axis=1)# 使用这函数获取的是一个series,使用axis函数可以修改sum的方向
# print(scores.iloc[:,1:])
#为Scores新增加一列数据
scores['总分']=scores.iloc[:,1:].sum(axis=1)
scores['平均分1']=scores.iloc[:,1:4].mean(axis=1)
scores['平均分2']=scores.总分/3
scores
# 找出数学高于140或者英语成绩高于50的学生
# 原来不加括号就会报错,记住了!
# scores[(scores.数学>140)| (scores.英语>50)]
#按照总分从高到低排序,输出前三名
# 有个by参数,就是指定参照那个参数排序,
scores.sort_values('总分',ascending=False).head(3)

   姓名   数学   语文   英语   总分        平均分1        平均分2
4  数学  150  139  100  389  129.666667  129.666667
2  赵六  132  145   98  375  125.000000  125.000000
3  招黑  147  128   78  353  117.666667  117.666667

In [77]:
data={
    '单位名称':['A','B','C','D','E'],
    '单价':[1,2,3,4,9],
    '销量':[12,35,8,9,10]
}
sales=pd.DataFrame(data)
sales
# 计算每种商品的销售额
#  找出销售额最高的产品
# 按照销售额排序,输出所有产品信息
#首先得到最重要的两列数据
sales[['单价','销量']]
sales['销售额']=sales[['单价','销量']].iloc[:,0]*sales[['单价','销量']].iloc[:,1]
sales.sort_values('销售额',ascending=False)
sales.head(1)


# 或者我们直接使用index完成这个对于列的获取,进而可以直接完成乘法操作
sales['销售额2']=sales['单价']*sales['销量']
sales

  单位名称  单价  销量  销售额  销售额2
0    A   1  12   12    12
1    B   2  35   70    70
2    C   3   8   24    24
3    D   4   9   36    36
4    E   9  10   90    90